/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CwCarousel {
        "arrows": boolean;
        "autoplay": boolean;
        "colors": string;
        "height": string;
        "index": boolean;
        "time": number;
        "width": string;
    }
    interface CwDraggable {
        "bgColor": string;
        "border": string;
        "gap": string;
        "height": string;
        "title": string;
        "transition": string;
        "width": string;
    }
}
declare global {
    interface HTMLCwCarouselElement extends Components.CwCarousel, HTMLStencilElement {
    }
    var HTMLCwCarouselElement: {
        prototype: HTMLCwCarouselElement;
        new (): HTMLCwCarouselElement;
    };
    interface HTMLCwDraggableElement extends Components.CwDraggable, HTMLStencilElement {
    }
    var HTMLCwDraggableElement: {
        prototype: HTMLCwDraggableElement;
        new (): HTMLCwDraggableElement;
    };
    interface HTMLElementTagNameMap {
        "cw-carousel": HTMLCwCarouselElement;
        "cw-draggable": HTMLCwDraggableElement;
    }
}
declare namespace LocalJSX {
    interface CwCarousel {
        "arrows"?: boolean;
        "autoplay"?: boolean;
        "colors"?: string;
        "height"?: string;
        "index"?: boolean;
        "time"?: number;
        "width"?: string;
    }
    interface CwDraggable {
        "bgColor"?: string;
        "border"?: string;
        "gap"?: string;
        "height"?: string;
        "title"?: string;
        "transition"?: string;
        "width"?: string;
    }
    interface IntrinsicElements {
        "cw-carousel": CwCarousel;
        "cw-draggable": CwDraggable;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cw-carousel": LocalJSX.CwCarousel & JSXBase.HTMLAttributes<HTMLCwCarouselElement>;
            "cw-draggable": LocalJSX.CwDraggable & JSXBase.HTMLAttributes<HTMLCwDraggableElement>;
        }
    }
}
