/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CwCarousel {
        "arrows": boolean;
        "autoplay": boolean;
        "colors": string;
        "height": string;
        "index": boolean;
        "time": number;
        "width": string;
    }
}
declare global {
    interface HTMLCwCarouselElement extends Components.CwCarousel, HTMLStencilElement {
    }
    var HTMLCwCarouselElement: {
        prototype: HTMLCwCarouselElement;
        new (): HTMLCwCarouselElement;
    };
    interface HTMLElementTagNameMap {
        "cw-carousel": HTMLCwCarouselElement;
    }
}
declare namespace LocalJSX {
    interface CwCarousel {
        "arrows"?: boolean;
        "autoplay"?: boolean;
        "colors"?: string;
        "height"?: string;
        "index"?: boolean;
        "time"?: number;
        "width"?: string;
    }
    interface IntrinsicElements {
        "cw-carousel": CwCarousel;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cw-carousel": LocalJSX.CwCarousel & JSXBase.HTMLAttributes<HTMLCwCarouselElement>;
        }
    }
}
